---
title: "Figures"
author: "Anshu Uppal"
date: "`r lubridate::today()`"
output: 
  html_document:
    code_folding: hide
knit: (function(input, ...) {
    rmarkdown::render(
      input, 
      output_dir = here::here("output")
    )
  })
---

```{r setup, results = "hide", message = FALSE, warning = FALSE}
knitr::opts_chunk$set(message = FALSE)  # Set default to not display code from chunks and not to display warnings
# options(width = 300)
# Load packages and dataset ####
pacman::p_load(    # Installs / loads packages if they are not already installed / loaded
  here,         # File locator
  # skimr,        # get overview of data
  tidyverse,    # data management + ggplot2 graphics 
  gtsummary,    # summary statistics and tests
  rstatix,      # summary statistics and statistical tests
  janitor,      # adding totals and percents to tables
  scales,       # easily convert proportions to percents  
  flextable,    # converting tables to pretty images
  lubridate,    # manipulate date objects
  ggfortify,    # plotting tools to check GLM assumptions
  apyramid,     # a package dedicated to creating age pyramids
  ggExtra,      # package for showing distributions of edges of geom_point()
  car,           # Used for checking non-collinearity assumption for regressions
  plotly
)

# Read in clean dataset (see "Merge code.R" and "Cleaning merged dataset")
dat <- tibble(readRDS(here("data", "clean_dataset.rds"))) #%>% 
  # drop_na(wfh_exposure, # Drop NAs in explanatory variables (2908 --> 2887)
  #                age_cat,sex_en,education_rec_en,
  #                hh_income_cat_en, finance_situation,
  #                hh_livewith_rec_en, overcrowded,
  #                noisy, quiet_room,
  #                health_general_dich)
dat <- dat %>% mutate(wfh_exposure = relevel(wfh_exposure, ref = "Yes, no change"))
```

Age pyramid
```{r}
dat %>% filter(sex_en != "Other") %>% # filter out the "Other" selections
  mutate(age_cat = factor(age_cat, levels = c("18-29", "30-39", "40-49", "50-59", "60+"))) %>% 
  apyramid::age_pyramid(age_group = "age_cat",
                        split_by = "sex_en"
                        # , proportional = TRUE     # Display as % of all cases instead of counts
  )+
  labs(title = "Age groups by sex", x = "Age category")+
  theme(legend.position = c(0.15,0.22))

```

Education
```{r}

```



EE-MBI score
```{r}
dat %>%
  ggplot(aes(x = burnout_score, fill = burnout_interp_dich30))+
  geom_histogram(binwidth = 1)+
  scale_fill_manual(values = c("lightseagreen", "#F8766D"))+
  labs(title = "Histogram of EE-MBI score (Severe \u2265 30)", x = "EE-MBI score")+
  theme_classic()+
  theme(legend.position = c(0.8,0.8),
        legend.title = element_blank())

dat %>% 
  count(burnout_interp_dich30) %>% 
  mutate(percent = n / sum(n))

dat %>%
  ggplot(aes(x = factor(burn_out), y = burnout_score))+
  geom_boxplot()+
  labs(title = "EE-MBI score by diagnosed burnout")+
  theme_classic()
```

Diagnosed burnout and EE-MBI
```{r}
dat %>% 
  mutate(burnout_score_cat = cut_width(burnout_score,width = 5, center = 2.5)) %>% 
  ggplot(aes(x=burnout_score_cat, y = burn_out))+
  geom_bar(position = "dodge", stat = "summary", na.rm = TRUE, fun = "mean")+
  theme_classic()+
  labs(x = "EE-MBI score in 5-point intervals", y = "Proportion diagnosed with burnout",
       title = "Proportion diagnosed with burnout in the last 12 months")+
  theme(axis.text.x = element_text(angle = 30))
```

WFH
```{r}
dat %>%
    ggplot(aes(x = wfh_exposure))+
    geom_bar()+
    labs(x = "Teleworking frequency and changes since the pandemic", title = "Distribution of Teleworking exposure variable")+
    theme_classic()

dat %>%
  group_by(education_rec_en) %>%
  count(wfh_exposure) %>%
  mutate(percent = 100 * n / sum(n)) %>% 
    ggplot(aes(x = wfh_exposure, y = scales::percent(percent)))+
    geom_col()+
    labs(x = "Teleworking frequency and changes since the pandemic", title = "Distribution of Teleworking exposure variable")+
    theme_classic()+
    theme(axis.text.x = element_text(angle = 20))+
  facet_wrap(.~education_rec_en)
```


```{r}
mcovariates <- c("wfh_exposure",
                 "age_cat","sex_en","education_rec_en",
                 "hh_income_cat_en", "finance_situation",
                 "hh_livewith_rec_en", "overcrowded",
                 "noisy", "quiet_room",
                 "health_general_dich"
                 )
mcov_names <- c("Teleworking frequency and change since pandemic",
                      "Age category",
                      "Sex",
                      "Education",
                      "Income",
                      "Financial situation",
                      "Living arrangement",
                      "Overcrowding",
                      "Noisy environment",
                      "Access to quiet room",
                      "General health (self-assessed)")
mcovariates <- cbind(mcovariates, mcov_names)
```

```{r,fig.width=4, fig.height=2.5}
for (i in 1:length(mcovariates[,1])) {
  fig <- dat %>%
  ggplot(aes(x= get(mcovariates[i,1]), y = burnout_score))+
  geom_boxplot()+
  labs(y = "EE-MBI score", x = mcovariates[i,2])+
  theme(axis.text.x = element_text(angle = 20))

  print(fig)
}
```

Entry into study
```{r}
dat %>% 
  ggplot(aes(x=date_soumission.x, fill = serocov_work.y))+
  geom_histogram(binwidth = 10)+
  theme(legend.position = c(0.8,0.8))
  
```

Positive impact on health
```{r}
dat %>%
  group_by(positive_impact) %>%
  count(wfh_exposure) %>%
  mutate(percent = 100 * n / sum(n)) %>% 
    ggplot(aes(x = wfh_exposure, y = scales::percent(percent)))+
    geom_col()+
    labs(x = "Teleworking frequency and changes since the pandemic", title = "Distribution of Teleworking exposure variable")+
    theme_classic()+
    theme(axis.text.x = element_text(angle = 20))+
  facet_wrap(.~positive_impact)
```

```{r}
ggplotly( dat %>% 
  ggplot(aes(x = physical_interaction, y = social_interaction, color = wfh_trich, label = paste(profession.y, "\n", Occupation_label)))+
  geom_point()+
  labs(color = "Teleworking")+
  geom_hline(yintercept = 0.5)+
  geom_vline(xintercept = 0.4)+
  theme_bw())
```

```{r}
dat %>% group_by(wfh_exposure) %>% 
  count(hh_income_cat_en) %>% 
  mutate(percent = round(n/sum(n)*100, 1)) %>% 
  ggplot(aes(x = hh_income_cat_en, y = percent))+
  labs(title = "Income group by Teleworking exposure")+
  geom_col()+
  facet_wrap(.~wfh_exposure)

dat %>% group_by(wfh_exposure) %>% 
  count(sex_en) %>% 
  mutate(percent = round(n/sum(n)*100, 1)) %>% 
  ggplot(aes(x = sex_en, y = percent))+
  labs(title = "Sex by Teleworking exposure")+
  geom_col()+
  facet_wrap(.~wfh_exposure)

dat %>% group_by(wfh_exposure) %>% 
  count(percent_change_cat) %>% 
  mutate(percent = round(n/sum(n)*100, 1)) %>% 
  ggplot(aes(x = percent_change_cat, y = percent))+
  labs(title = "Change in working hours by Teleworking exposure")+
  geom_col()+
  facet_wrap(.~wfh_exposure)

dat %>% group_by(wfh_exposure) %>% 
  count(age_cat) %>% 
  mutate(percent = round(n/sum(n)*100, 1)) %>% 
  ggplot(aes(x = age_cat, y = percent))+
  labs(title = "Age category by Teleworking exposure")+
  geom_col()+
  facet_wrap(.~wfh_exposure)

dat %>% group_by(wfh_exposure) %>% 
  count(supervision_short) %>% 
  mutate(percent = round(n/sum(n)*100, 1)) %>% 
  ggplot(aes(x = supervision_short, y = percent))+
  labs(title = "Managerial duties by Teleworking exposure")+
  geom_col()+
  facet_wrap(.~wfh_exposure)

```


```{r}
dat %>% group_by(wfh_exposure) %>% 
  count(work_life_balance) %>% 
  mutate(percent = round(n/sum(n)*100, 1)) %>% 
  ggplot(aes(x = work_life_balance, y = percent))+
  labs(title = "Work-life balance by Teleworking exposure")+
  geom_col()+
  facet_wrap(.~wfh_exposure)
```

