---
title: "Descriptive analyses"
author: "Anshu Uppal"
date: "17/02/2023"
output: 
  html_document:
    code_folding: hide
knit: (function(input, ...) {
    rmarkdown::render(
      input, 
      output_dir = here::here("output")
    )
  })
---

```{r setup, results = "hide", message = FALSE, warning = FALSE}
knitr::opts_chunk$set(message = FALSE)  # Set default to not display code from chunks and not to display warnings
options(width = 300)
# Load packages and dataset ####
pacman::p_load(    # Installs / loads packages if they are not already installed / loaded
  rio,          # File import
  here,         # File locator
  skimr,        # get overview of data
  tidyverse,    # data management + ggplot2 graphics 
  gtsummary,    # summary statistics and tests
  rstatix,      # summary statistics and statistical tests
  janitor,      # adding totals and percents to tables
  scales,       # easily convert proportions to percents  
  flextable,    # converting tables to pretty images
  lubridate,     # manipulate date objects
  apyramid      # a package dedicated to creating age pyramids
)

# Read in clean dataset (see "Merge code.R" and "Cleaning merged dataset")
dat <- tibble(readRDS(here("data", "clean_dataset.rds")))
dat_all <- tibble(readRDS(here("data", "clean_dataset_incl_salariee.rds")))
```

## Summary tables, stratified by: {.tabset}
<!-- ############################################################## -->
<!-- Make a generic table without stratification, for later merging -->
<!-- ############################################################## -->
```{r tbl1_col_totals}

#####
####### Make the list of variables to include - this will be used for all tables
#####
var_included <- c("work_situation.y_dich",
  "burnout_score", "burn_out", "burnout_interp_dich", "feeling_exhausted_dich", "wfh", "wfh_cat", "wfh_change", "wfh_exposure", "wfh_balance",
  # "serocov_work.y", "serocov_pop.y","sp4_avril_2022.y",
  "sex_en", "age_cat", "bmi_4_cat_en", "education_rec_en", "Swiss_nat", "ethnicity_dct", "ethn_dich",
  # "relation", "children", "hh_livewith", "hh_composition", "zone_house",
  # "housing_condition", "noisy", "quiet_room", "smoking_rec_en", "sedentary_work",
  # "multiple_salaried_jobs", "job_sector", "hh_income_cat_en", "workplace_size", "workplace_size_dich", "supervision",
  # # "wfh_change", "wfh_balance", 
  # "finance_situation", "financial_difficulties",
  # "fear_losing_job", "fear_losing_job_dich", "work_interruption", "work_interruption_dich",
  # "exercise_hard", "exercise_hard_dich", "exercise_moderate", "exercise_moderate_dich",
  "health_general_dich", "mental_state_dich", "chronic_disease")

# ## Table of totals for the variables included ##
# tbl1_col <- dat %>% select(all_of(var_included)) %>% 
#   tbl_summary(
#     percent = "col",                         # calculate percent column-wise
#     label  = list(
#       sex_en   ~ "Sex",
#       age_cat ~ "Age category (years)",
#       education_rec_en ~ "Education",
#       Swiss_nat ~ "Nationality"
#     ),
#     type = all_categorical() ~ "categorical",                 # force all categorical levels to display
#     missing_text = "Missing"                                   # how missing values should display
#   ) %>%
#   add_n() %>%                                        # Number of non-missing values
#   modify_header(all_stat_cols() ~ "**Overall**") %>% 
#   modify_spanning_header(everything() ~ NA) %>% 
#   modify_footnote(all_stat_cols() ~ "Column-wise %") # ; tbl1_col
```



```{r tbl1_mbi_score}
tbl1_mbi_score <- dat %>% select(all_of(var_included)) %>% 
  tbl_summary(
    by = burnout_score,
    # percent = "row",                         # calculate percent row-wise
    label  = list(
      sex_en   ~ "Sex",
      age_cat ~ "Age category (years)",
      education_rec_en ~ "Education",
      Swiss_nat ~ "Nationality"
                ),
    # type = all_categorical() ~ "categorical",                 # force all categorical levels to display
    missing_text = "Missing"                                  # how missing values should display
) %>% 
  modify_spanning_header(all_stat_cols() ~ "**MBI (EE) Score**") #%>% 
  # modify_footnote(all_stat_cols() ~ "Row-wise %")
  tbl1_mbi_score
```

<!-- ### MBI score -->
<!-- ```{r} -->
<!-- tbl1_mbi_score_combined <- -->
<!--   tbl_merge( -->
<!--     tbls = list(tbl1_col, tbl1_mbi_score), -->
<!--     tab_spanner = c(NA, "**EE-MBI score**") -->
<!--       ) ; tbl1_mbi_score_combined -->
<!-- ``` -->